### PR TITLE
Make window follow cursor on every redraw

### PR DESCRIPTION
**Pull request by kitt-cat**
Not sure if there might be a better way, but it appears to work.

### CODE REVIEW

**Comment by arp242** [comment]
> repaint transparency, otherwise window 'drags' a bit of whatever was under it originally with it wherever it goes

This is also the problem I noticed from your testing your first commit. It wasn't caused it it, though; it just makes it more noticeable.

However, your second commit makes the entire background black for me (?) I just get a black circle.

**Comment by kitt-cat** [comment]
Huh. Are you running a compositor?

**Comment by arp242** [comment]
No, just PekWM (which is a bit of an obscure WM, but has been around for a long while and is very stable).

**Comment by arp242** [comment]
Apparently it's a known problem: https://wiki.archlinux.org/index.php/PekWM#Compositing.2Ftransparency_does_not_work_properly

**Comment by kitt-cat** [comment]
I see. I can reproduce the black background if I stop compton first (on i3).
I believe a compositor is more or less required for true transparency.

**Comment by arp242** [comment]
Right. That would explain that then. I'm a simple guy with simple window managing needs; never looked much at all this transparency and other newfangled stuff :-)

Should probably create an option for this. I just moved some options around to free the `-t` (`--transparency`) for this (sorry 'bout the merge conflict).

I think it's probably also useful to make a flag to disable the tracking of the mouse cursor? `-n`/`--no-track`? Not a great name, but can't think of anything better atm.

**Comment by kitt-cat** [comment]
Perhaps `-f` `--follow-cursor`?

**Comment by arp242** [comment]
But it makes sense to enable it by default, I think? So it'd have to be `--no-follow-cursor`?

**Comment by arp242** [comment]
Ugh, I wanted to add a commit to add the `-f`and `-t` options, and now I've blown this entire PR away (?!)

I hate git.

**Comment by arp242** [comment]
Well, I've just put it all in master now. `-f` and `-t` are optional and disabled by default, since it doesn't work for everyone.

Thanks for the patch, and let me know if you have problems.

**Pull request closed without merging**
